### PR TITLE
Testing

### PR DESCRIPTION
**Pull request by CindyHoang**
:)

### CODE REVIEW

**Comment by zzmarkzz321** [comment]
👍

**Review by cjsimon — APPROVED** [review]
Looks good. Much amaze

**Review by zzmarkzz321 — CHANGES_REQUESTED** [review]
Use the standard format for opening html:
```html
<!DOCTYPE html>
<html>

</html>
```

**Comment by CindyHoang** [comment]
Changes to be made in future branch :)

**Pull request merged**
